<?php
/**
 * This file is important to all pages changes can be made to constants if  the 
 * need arises
 * @author Ibrahim Isa
 * @version 1.0
 * @link http://www.iblynks.com
 */
?>
<div class='system-head'>
    <page><span>&raquo;</span>Dashboard</page>
</div>

<div class='system-content'> 
    <function>
            <a class='child' href='?nav=nw-admin-account'>
                <i style="background-image:url('<?php echo NW_ADMIN_FUNIMG?>/address-one.png')" ></i>
                <h3>Account Information</h3>
            </a>
            <a class='child' href='?nav=nw-admin-interview'>
                <i style="background-image:url('<?php echo NW_ADMIN_FUNIMG?>/inter.png')" ></i>
                <h3>Interviews</h3>
            </a>
            <a class='child child-end' href='<?php echo NW_DEFURL?>?nav=nw-jobs' target="_new">
                 <i style="background-image:url('<?php echo NW_ADMIN_FUNIMG?>/forum.png')" ></i>
                <h3>Comments</h3>
            </a>
            <a class='child' href='?nav=nw-admin-users'>
                 <i style="background-image:url('<?php echo NW_ADMIN_FUNIMG?>/user-one.png')" ></i>
                <h3>Manage Users</h3>
            </a>
            <a class='child' href='?nav=nw-admin-alert'>
                 <i style="background-image:url('<?php echo NW_ADMIN_FUNIMG?>/email-2.png')" ></i>
                <h3>Feedbacks</h3>
            </a>
            <a class='child child-end' href='?nav=nw-admin-jobs'>
                <i style="background-image:url('<?php echo NW_ADMIN_FUNIMG?>/products.png')" ></i>
                <h3>Jobs Inventory</h3>
            </a>
            <a class='child' href='?nav=nw-admin-reg'>
                 <i style="background-image:url('<?php echo NW_ADMIN_FUNIMG?>/report.png')" ></i>
                <h3>Region</h3>
            </a>
            <a class='child' href='?nav=nw-admin-ind'>
                 <i style="background-image:url('<?php echo NW_ADMIN_FUNIMG?>/database.png')" ></i>
                <h3>Industries</h3>
            </a>
            <a class='child child-end' href='?nav=nw-admin-set'>
                <i style="background-image:url('<?php echo NW_USR_FUNC?>lock-two.png')" ></i>
                <h3>Change password</h3>
            </a>
    </function>
</div>