<?php
/**
 * This file is important to all pages changes can be made to constants if  the 
 * need arises
 * @author Ibrahim Isa
 * @version 1.0
 * @link http://www.iblynks.com
 */

//$message = system_message('error','Invalid Username or password','gen-margin-one');

?>
<div class='system-head'>
    <page><span>&raquo;</span>Account Information</page>
</div>

<div class='system-content'> 
    <content>
        <div class='top-content'>
            <div>
                
            </div>
        </div>
    </content>
</div>