<?php
/**
 * This file is important to all pages changes can be made to constants if  the 
 * need arises
 * @author Ibrahim Isa
 * @version 1.0
 * @link http://www.iblynks.com
 */
?>
<div class='system-head'>
    <page><span>&raquo;</span>Interview</page>
</div>

<div class='system-content'> 
    <content>
        <div class='system-loading-one'>
            <p><img src='<?php echo NW_IMAGE_URL?>gif/unc-small.gif' /></p>
            <p>system loading</p>
        </div>
    </content>
</div>