<?php
/**
 * Java script ajax jquery
 * 
 * This file is important to all pages changes can be made to constants if  the 
 * need arises
 * @author Ibrahim Isa
 * @version 1.0
 * @package Template
 * @link http://www.iblynks.com
 */
/**
 *  Include Config file
 */
include('../nw-config.php');
/**
 *  Include General Class
 */
include (NW_GENERAL_CLASS);
/**
 *  Include Function File
 */
include (NW_GENERAL_FUNCTION);
