<?php
/**
 * Sn-user-login
 * 
 * This file is important to all pages changes can be made to constants if  the 
 * need arises
 * @author Ibrahim Isa
 * @version 1.0
 * @package Template
 * @link http://www.iblynks.com
 */
?>

<script> </script>

<?php DynDiv('H','Job Applications');?>

      <div class='general-content'>
          
               <div class='generalFadediv genFadediv-border-radius'></div>    
               <div class='hold-jquery'>
                   <form action='#' method='post'>
                        <div class='top-content'>
                            <div class='system-loading-one'>
                                 <p><img src='<?php echo NW_IMAGE_URL?>general/data.png' /></p>
                                 <p>No data yet</p>
                            </div>
                        </div>
                   </form>
               </div>
                   
      </div>

<?php DynDiv('F','');?>

